services:
  migrate:
    image: ghcr.io/collegiumacademicum/cartei-db:latest
    env_file: .env
    restart: on-failure

  app:
    image: ghcr.io/collegiumacademicum/cartei-web:latest
    env_file: .env
    volumes:
      - ./certs:/app/certs:ro,z
    networks:
      - www
    depends_on:
      - migrate
    restart: unless-stopped

networks:
  www:
    external: true
